# Generated by Django 2.0.3 on 2018-06-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mob_tracker', '0002_auto_20180604_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='entries',
        ),
        migrations.AddField(
            model_name='entry',
            name='contributors',
            field=models.ManyToManyField(to='mob_tracker.Profile'),
        ),
    ]
