# Generated by Django 2.0.3 on 2018-06-05 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mob_tracker', '0003_auto_20180604_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='entries',
            field=models.ManyToManyField(blank=True, to='mob_tracker.Entry'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='contributors',
            field=models.ManyToManyField(blank=True, to='mob_tracker.Profile'),
        ),
        migrations.AlterModelTable(
            name='entry',
            table='mob_tracker_entry_contributors',
        ),
    ]
