# Generated by Django 2.0.3 on 2018-06-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mob_tracker', '0004_tip_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='title_clean',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tip',
            name='color',
            field=models.CharField(default='255,255,255', max_length=11),
        ),
    ]
