# Generated by Django 2.0.3 on 2018-06-05 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mob_tracker', '0004_auto_20180604_1707'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='entry',
            table=None,
        ),
    ]
